services:

  postgres:
    image: postgres:16

    container_name: postgres-bcb

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: bcb_data

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4

    container_name: pgadmin-bcb

    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin

    ports:
      - "5050:80"

    depends_on:
      - postgres

  spark:
    build:
      context: ..
      dockerfile: docker/spark/Dockerfile

    container_name: spark-bcb

    ports:
      - "8080:8080"
      - "7077:7077"

    volumes:
      - ../:/app

    working_dir: /app

    tty: true

volumes:
  postgres_data: