version: '3.8'

services:

  postgres:
    image: postgres:16
    container_name: postgres-bcb
    restart: unless-stopped

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: bcb_data

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-bcb
    restart: unless-stopped

    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin

    ports:
      - "5050:80"

    depends_on:
      - postgres

  airflow:
    build:
      context: ..
      dockerfile: docker/airflow/Dockerfile

    container_name: airflow-bcb
    restart: unless-stopped

    depends_on:
      - postgres

    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://admin:admin@postgres:5432/bcb_data
      AIRFLOW__CORE__FERNET_KEY: ""
      JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64

    command: >
      bash -c "
        airflow db migrate &&
        airflow users create
        --username admin
        --firstname Admin
        --lastname User
        --role Admin
        --email admin@admin.com
        --password admin || true &&
        airflow standalone
      "

    ports:
      - "8081:8080"

    volumes:
      - ../airflow/dags:/opt/airflow/dags
      - ..:/app

    working_dir: /app

  spark:
    build:
      context: ..
      dockerfile: docker/spark/Dockerfile

    container_name: spark-bcb
    restart: unless-stopped

    ports:
      - "8080:8080"
      - "7077:7077"

    volumes:
      - ..:/app

    working_dir: /app

    tty: true

  streamlit:
    build:
      context: ..
      dockerfile: docker/streamlit/Dockerfile

    container_name: streamlit-bcb
    restart: unless-stopped

    environment:
      DB_HOST: postgres-bcb
      OLLAMA_HOST: http://host.docker.internal:11434

    ports:
      - "8501:8501"

    depends_on:
      - postgres

    volumes:
      - ..:/app

    working_dir: /app

  zookeeper:
      image: confluentinc/cp-zookeeper:7.6.0
      container_name: zookeeper-bcb
      restart: unless-stopped

      environment:
        ZOOKEEPER_CLIENT_PORT: 2181
        ZOOKEEPER_TICK_TIME: 2000

      ports:
        - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka-bcb
    restart: unless-stopped

    depends_on:
      - zookeeper

    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-bcb:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-bcb:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

    ports:
      - "9092:9092"
      - "29092:29092"

  n8n:
      image: n8nio/n8n:latest
      container_name: n8n-bcb
      restart: unless-stopped

      environment:
        N8N_HOST: localhost
        N8N_PORT: 5678
        N8N_PROTOCOL: http
        WEBHOOK_URL: http://localhost:5678

      ports:
        - "5678:5678"

      volumes:
        - n8n_data:/home/node/.n8n

volumes:
  postgres_data:
  n8n_data: